# Example benchmark configuration
log-level: info
path:
  material: /tmp/orion-benchmark/material
  data: /tmp/orion-benchmark/data
  metrics: /tmp/orion-benchmark/metrics
  default-local-conf: local-config.yaml
  default-shared-conf: shared-config.yaml
  default-prometheus-conf: prometheus.yaml
cluster:
  # Each node will serve at port+rank
  node-base-port: 6000
  peer-base-port: 7000
  prometheus-base-port: 2000
  data-size-collection-interval: 10s
  nodes:
    - 127.0.0.1
workload:
  name: independent-blind-writes
  user-count: 512
  parameters:
    lines-per-user: 100
  session:
    tx-timeout: 10
    query-timeout: 10
  duration: 2m
  log-report-interval: 10s
  # Each worker will serve at port+rank
  prometheus-base-port: 3000
  # Each worker might run many parallel workloads
  workers:
    - 127.0.0.1
    - 127.0.0.1
prometheus:
  listen-address: 0.0.0.0:9099
