# Example benchmark configuration
log-level: debug
session:
  tx-timeout: 60
  query-timeout: 60
material-path: /tmp/orion-benchmark-material
data-path: /tmp/orion-benchmark-data
user-count: 5
workload: independent-increment
cluster:
  main:
    address: 127.0.0.1
    raft-id: 1
    node-port: 6000
    peer-port: 7000