# Example benchmark configuration
log-level: info
path:
  material: /tmp/orion-benchmark/material
  data: /tmp/orion-benchmark/data
  metrics: /tmp/orion-benchmark/metrics
  default-local-conf: local-config.yaml
  default-shared-conf: shared-config.yaml
  default-prometheus-conf: prometheus.yaml
cluster:
  # Each node will serve at port+rank
  node-base-port: 6000
  peer-base-port: 7000
  prometheus-base-port: 2000
  data-size-collection-interval: 10s
  nodes:
    - 127.0.0.1
workload:
  name: independent
  user-count: 1_000
  warmup-operations:
    - operation: -write 1_000 -acl 0
  operations:
#    - operation: -read 5
#      weight: 10
#    - operation: -query 50
#      weight: 70
    - operation: -write 1 -acl 0
      weight: 20
  parameters:
    lines-per-user: 1_000
    commits-per-sync: 0
  session:
    tx-timeout: 2m
    query-timeout: 1m
    backoff:
      initial-interval: 10ms
      max-interval: 5s
  duration: 3m
  warmup-duration: 5h
  # Each worker will serve at port+rank
  prometheus-base-port: 3000
  # Each worker might run many parallel workloads
  workers:
    - 127.0.0.1
    - 127.0.0.1
prometheus:
  listen-address: 0.0.0.0:9099
