server:
  loglevel: info
  database:
    name: leveldb
  provenance:
    disabled: true
  queuelength:
    transaction: 50_000
    reorderedtransactionbatch: 2
    # ignored
    block: 1
  queryprocessing:
    responsesizelimitinbytes: 1_000_000
  tls:
    enabled: false
blockcreation:
  maxblocksize: 100_000_000_000
  maxtransactioncountperblock: 50_000
  blocktimeout: 10s
replication:
  tls:
    enabled: false
experimental:
  disablecommitphasesigvalidation: false
