server:
  loglevel: info
  database:
    name: leveldb
  provenance:
    disabled: true
  queuelength:
    transaction: 50_000
    reorderedtransactionbatch: 2
    # ignored
    block: 100_000
  queryprocessing:
    responsesizelimitinbytes: 1_000_000
  tls:
    enabled: false
blockcreation:
  maxblocksize: 1_000_000_000
  maxtransactioncountperblock: 100_000
  blocktimeout: 0.01s
replication:
  tls:
    enabled: false
